### ISSUE TITLE
JavaScript error "Uncaught TypeError" when menu is disabled in perspective

### ISSUE THREAD

**Issue by APochmann** [pimcore/file-explorer-bundle#23]
In case there are perspectives defined which hide the extras menu the following JavaScript exception occurs:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'items')
    at klass.preMenuBuild
```

The reason is `const filteredMenu = menu.extras.items.filter(...` where `menu.extras` is `undefined` as the menu is deactivated

Surrounding the code block in `preMenuBuild` event listener in `startup.js` with an if statement would fix the issue:
```
        if (menu.extras) {
            const filteredMenu = menu.extras.items.filter(function (item) {
                return item.itemId === 'pimcore_menu_extras_system_info';
            });

            const systemInfoMenu = filteredMenu.shift();
            systemInfoMenuItems.map(function(item) {
                systemInfoMenu.menu.items.push(item);
            });
        }
```

**Comment by martineiber** [comment]
Fixed by https://github.com/pimcore/file-explorer-bundle/pull/25
