### ISSUE TITLE
[Bug] File can not be opend. 

### ISSUE THREAD

**Issue by martineiber** [pimcore/file-explorer-bundle#9]
When trying to open a file, the following error appears.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/11687066/231793501-280f5305-7424-4baa-b360-7eb7871f6ab2.png">

`admin/theme-chrome.js` can not be found.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/14
